name: Weather CI  # Имя Workflow, которое будет отображаться в интерфейсе GitHub

on:
  push:  # Триггер события, который запускает этот Workflow
    branches: [ "main" ] # Указываем, что нас интересуют только пуши в определенные ветки

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: weather_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: weather_db
      DB_USER: postgres
      DB_PASSWORD: postgres




    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23.0.1'
          distribution: ''

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run Liquibase migrations
        run: |
          ./gradlew update \
            -Pliquibase.url=jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME \
            -Pliquibase.username=$DB_USER \
            -Pliquibase.password=$DB_PASSWORD